package fr.gkj.ws.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-03-12T09:08:31.810+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://ws.gkj.fr/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws.gkj.fr/", className = "fr.gkj.ws.hello.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws.gkj.fr/", className = "fr.gkj.ws.hello.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello(
        @WebParam(name = "texte", targetNamespace = "")
        java.lang.String texte
    );
}
