package ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-03-14T15:46:24.255+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://ws/", name = "BanqueService")
@XmlSeeAlso({ObjectFactory.class})
public interface BanqueService {

    @WebMethod
    @Action(input = "http://ws/BanqueService/getCompteRequest", output = "http://ws/BanqueService/getCompteResponse")
    @RequestWrapper(localName = "getCompte", targetNamespace = "http://ws/", className = "ws.GetCompte")
    @ResponseWrapper(localName = "getCompteResponse", targetNamespace = "http://ws/", className = "ws.GetCompteResponse")
    @WebResult(name = "return", targetNamespace = "")
    public ws.Compte getCompte(
        @WebParam(name = "code", targetNamespace = "")
        long code
    );

    @WebMethod
    @Action(input = "http://ws/BanqueService/getComptesRequest", output = "http://ws/BanqueService/getComptesResponse")
    @RequestWrapper(localName = "getComptes", targetNamespace = "http://ws/", className = "ws.GetComptes")
    @ResponseWrapper(localName = "getComptesResponse", targetNamespace = "http://ws/", className = "ws.GetComptesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<ws.Compte> getComptes();

    @WebMethod
    @Action(input = "http://ws/BanqueService/conversionEuroToDRequest", output = "http://ws/BanqueService/conversionEuroToDResponse")
    @RequestWrapper(localName = "conversionEuroToD", targetNamespace = "http://ws/", className = "ws.ConversionEuroToD")
    @ResponseWrapper(localName = "conversionEuroToDResponse", targetNamespace = "http://ws/", className = "ws.ConversionEuroToDResponse")
    @WebResult(name = "return", targetNamespace = "")
    public double conversionEuroToD(
        @WebParam(name = "montant", targetNamespace = "")
        double montant
    );
}
