package ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-03-14T15:46:24.265+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "BanqueWS", 
                  wsdlLocation = "http://localhost:8080/BanqueWS?wsdl",
                  targetNamespace = "http://ws/") 
public class BanqueWS extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws/", "BanqueWS");
    public final static QName BanqueServicePort = new QName("http://ws/", "BanqueServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/BanqueWS?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BanqueWS.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/BanqueWS?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BanqueWS(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BanqueWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BanqueWS() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BanqueWS(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BanqueWS(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public BanqueWS(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort() {
        return super.getPort(BanqueServicePort, BanqueService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BanqueService
     */
    @WebEndpoint(name = "BanqueServicePort")
    public BanqueService getBanqueServicePort(WebServiceFeature... features) {
        return super.getPort(BanqueServicePort, BanqueService.class, features);
    }

}
