
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package ws;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-03-14T15:46:24.236+01:00
 * Generated source version: 2.6.2
 * 
 */

@javax.jws.WebService(
                      serviceName = "BanqueWS",
                      portName = "BanqueServicePort",
                      targetNamespace = "http://ws/",
                      wsdlLocation = "http://localhost:8080/BanqueWS?wsdl",
                      endpointInterface = "ws.BanqueService")
                      
public class BanqueServiceImpl implements BanqueService {

    private static final Logger LOG = Logger.getLogger(BanqueServiceImpl.class.getName());

    /* (non-Javadoc)
     * @see ws.BanqueService#getCompte(long  code )*
     */
    public ws.Compte getCompte(long code) { 
        LOG.info("Executing operation getCompte");
        System.out.println(code);
        try {
            ws.Compte _return = new ws.Compte();
            _return.setCode(-1676755646205671182l);
            _return.setSolde(0.060790632351793494);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ws.BanqueService#getComptes(*
     */
    public java.util.List<ws.Compte> getComptes() { 
        LOG.info("Executing operation getComptes");
        try {
            java.util.List<ws.Compte> _return = new java.util.ArrayList<ws.Compte>();
            ws.Compte _returnVal1 = new ws.Compte();
            _returnVal1.setCode(3895339506477135401l);
            _returnVal1.setSolde(0.5794346661512172);
            _return.add(_returnVal1);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see ws.BanqueService#conversionEuroToD(double  montant )*
     */
    public double conversionEuroToD(double montant) { 
        LOG.info("Executing operation conversionEuroToD");
        System.out.println(montant);
        try {
            double _return = 0.7312084389245722;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
