package net.webservicex;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-03-13T11:07:41.009+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebServiceClient(name = "lengthUnit", 
                  wsdlLocation = "http://www.webservicex.net/length.asmx?WSDL",
                  targetNamespace = "http://www.webserviceX.NET/") 
public class LengthUnit extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.webserviceX.NET/", "lengthUnit");
    public final static QName LengthUnitHttpGet = new QName("http://www.webserviceX.NET/", "lengthUnitHttpGet");
    public final static QName LengthUnitHttpPost = new QName("http://www.webserviceX.NET/", "lengthUnitHttpPost");
    public final static QName LengthUnitSoap = new QName("http://www.webserviceX.NET/", "lengthUnitSoap");
    public final static QName LengthUnitSoap12 = new QName("http://www.webserviceX.NET/", "lengthUnitSoap12");
    static {
        URL url = null;
        try {
            url = new URL("http://www.webservicex.net/length.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LengthUnit.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://www.webservicex.net/length.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public LengthUnit(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LengthUnit(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LengthUnit() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LengthUnit(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LengthUnit(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public LengthUnit(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns LengthUnitHttpGet
     */
    @WebEndpoint(name = "lengthUnitHttpGet")
    public LengthUnitHttpGet getLengthUnitHttpGet() {
        return super.getPort(LengthUnitHttpGet, LengthUnitHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LengthUnitHttpGet
     */
    @WebEndpoint(name = "lengthUnitHttpGet")
    public LengthUnitHttpGet getLengthUnitHttpGet(WebServiceFeature... features) {
        return super.getPort(LengthUnitHttpGet, LengthUnitHttpGet.class, features);
    }
    /**
     *
     * @return
     *     returns LengthUnitHttpPost
     */
    @WebEndpoint(name = "lengthUnitHttpPost")
    public LengthUnitHttpPost getLengthUnitHttpPost() {
        return super.getPort(LengthUnitHttpPost, LengthUnitHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LengthUnitHttpPost
     */
    @WebEndpoint(name = "lengthUnitHttpPost")
    public LengthUnitHttpPost getLengthUnitHttpPost(WebServiceFeature... features) {
        return super.getPort(LengthUnitHttpPost, LengthUnitHttpPost.class, features);
    }
    /**
     *
     * @return
     *     returns LengthUnitSoap
     */
    @WebEndpoint(name = "lengthUnitSoap")
    public LengthUnitSoap getLengthUnitSoap() {
        return super.getPort(LengthUnitSoap, LengthUnitSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LengthUnitSoap
     */
    @WebEndpoint(name = "lengthUnitSoap")
    public LengthUnitSoap getLengthUnitSoap(WebServiceFeature... features) {
        return super.getPort(LengthUnitSoap, LengthUnitSoap.class, features);
    }
    /**
     *
     * @return
     *     returns LengthUnitSoap
     */
    @WebEndpoint(name = "lengthUnitSoap12")
    public LengthUnitSoap getLengthUnitSoap12() {
        return super.getPort(LengthUnitSoap12, LengthUnitSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LengthUnitSoap
     */
    @WebEndpoint(name = "lengthUnitSoap12")
    public LengthUnitSoap getLengthUnitSoap12(WebServiceFeature... features) {
        return super.getPort(LengthUnitSoap12, LengthUnitSoap.class, features);
    }

}
