
package net.webservicex;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-03-13T11:07:40.030+01:00
 * Generated source version: 2.6.2
 * 
 */
public final class LengthUnitHttpGet_LengthUnitHttpGet_Client {

    private static final QName SERVICE_NAME = new QName("http://www.webserviceX.NET/", "lengthUnit");

    private LengthUnitHttpGet_LengthUnitHttpGet_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = LengthUnit.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        LengthUnit ss = new LengthUnit(wsdlURL, SERVICE_NAME);
        LengthUnitHttpGet port = ss.getLengthUnitHttpGet();  
        
        {
        System.out.println("Invoking changeLengthUnit...");
        java.lang.String _changeLengthUnit_lengthValue = "_changeLengthUnit_lengthValue1054461341";
        java.lang.String _changeLengthUnit_fromLengthUnit = "_changeLengthUnit_fromLengthUnit2039705031";
        java.lang.String _changeLengthUnit_toLengthUnit = "_changeLengthUnit_toLengthUnit614200263";
        double _changeLengthUnit__return = port.changeLengthUnit(_changeLengthUnit_lengthValue, _changeLengthUnit_fromLengthUnit, _changeLengthUnit_toLengthUnit);
        System.out.println("changeLengthUnit.result=" + _changeLengthUnit__return);


        }

        System.exit(0);
    }

}
