package net.webservicex;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.2
 * 2018-03-13T11:07:41.002+01:00
 * Generated source version: 2.6.2
 * 
 */
@WebService(targetNamespace = "http://www.webserviceX.NET/", name = "lengthUnitSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface LengthUnitSoap {

    @WebMethod(operationName = "ChangeLengthUnit", action = "http://www.webserviceX.NET/ChangeLengthUnit")
    @RequestWrapper(localName = "ChangeLengthUnit", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeLengthUnit")
    @ResponseWrapper(localName = "ChangeLengthUnitResponse", targetNamespace = "http://www.webserviceX.NET/", className = "net.webservicex.ChangeLengthUnitResponse")
    @WebResult(name = "ChangeLengthUnitResult", targetNamespace = "http://www.webserviceX.NET/")
    public double changeLengthUnit(
        @WebParam(name = "LengthValue", targetNamespace = "http://www.webserviceX.NET/")
        double lengthValue,
        @WebParam(name = "fromLengthUnit", targetNamespace = "http://www.webserviceX.NET/")
        net.webservicex.Lengths fromLengthUnit,
        @WebParam(name = "toLengthUnit", targetNamespace = "http://www.webserviceX.NET/")
        net.webservicex.Lengths toLengthUnit
    );
}
